dataset_params:
  im_path: 'data/train/images'

diffusion_params:
  num_timesteps : 50
  beta_start : 0.000001
  beta_end : 0.5

model_params:
  im_channels : 1
  im_size : 16    
  time_horizon: 256
  down_channels : [32, 64, 128, 256]
  mid_channels : [256, 256, 128]
  down_sample : [True, True, False]
  time_emb_dim : 128
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2
  num_heads : 8

train_params:
  task_name: 'default'
  batch_size: 16
  num_epochs: 500
  num_samples : 50
  num_grid_rows : 10
  lr: 0.0001
  ckpt_name: 'ddpm_ckpt.pth'
